Refonte complète de pot2pad et pad2po
sur le modèle de pad-convert-0.23
http://agir.april.org/issues/1402
Les liens sont extraits et réinsérés.

diff --git a/pad2po b/pad2po
--- a/pad2po
+++ b/pad2po
@@ -1,153 +1,232 @@
 #!/bin/bash
 
-# PAD to PO converter
+# NAME
+#    pad2po - PAD to PO converter
 
+# SYNOPSIS
+#    pad2po [/path/to/NAME.txt]
 
-# Overview:
-# This script converts a translated pad, created with html-to-pad or
-# pot-to-pad, into a gnu.org PO file; it fills out the PO header with generic
-# data (charset, encoding, language, team address).
+# DESCRIPTION
+#    This script converts a translated pad, created with html-to-pad or
+#    pot-to-pad (with link extraction), into a gnu.org PO file and fills out
+#    the PO header with generic data (charset, encoding, language, team
+#    address). It can be launched from the application and contextual menus of
+#    GNOME or KDE.
 
-# Requirements:
-# The working directory should contain NAME.pot and the exported pad
-# (EnFr-NAME.txt).
+# REQUIREMENTS
+#    * The pad must have been created by pot2pad, or html2pad from
+#      pad-convert-0.21+.
+#    * The working directory (wdir) is $HOME/pad. This can  be  changed  by
+#      modifying one line in the script.
+#    * NAME.pot must be at the proper place in the www directory.
+#    * No  blank line between an original paragraph and its translation, or
+#      between the string or link label and  the original. But the translation
+#      may be blank.
+#    * No spurious LFs!
 
-# How-to:
-# - Export the translated pad to the working directory (default:
-#   $HOME/Bureau/pad) as plain text.
-# - Launch the script or run it from a terminal.
-# - Add the translator's notes by hand, if any.
-# - Finish up in the PO editor.
-# - To convert the same EnFr-NAME.txt again, the corresponding PO file needs
-#   to be removed from the working directory.
+# OPTIONS
+#    None yet.
+
+# OUTPUT, WARNINGS and ERRORS
+#    NAME.fr.po and possibly NAME.warn are created in the working directory.
+#    The exit code is 1 if the input file does not have the .txt extension
+#    or is empty, 2 if there are warnings, 0 otherwise.
+
+# HOW-TO
+#    1. Export the translated pad as plain text.
+#    2. Launch the script as explained in pot2pad.
+#    3. Add the translator's notes by hand, if any.
+#       TODO: try to insert them automatically.
+#    4. Finish up in the PO editor.
 
 # Copyright (C) 2013 Whoever.
 # You may redistribute this script and/or modify it under the terms of the
 # Creative Commons CC0 license
 # (http://creativecommons.org/publicdomain/zero/1.0/legalcode).
 
+wdir=$HOME/pad
+
 set -e
-mkdir -p $HOME/pad && cd $HOME/pad
+mkdir -p $wdir
 
-echo "
- ## pad2po : Conversion d'un pad en fichier PO ##
-"
-
-# Create temporary files.
-TMP1=$(mktemp -t pad2po.XXXXXX) || exit 1 # List of translated pads, pruned
-TMP2=$(mktemp -t pad2po.XXXXXX) || exit 1 # List of POs / tr. strings / header
-TMP3=$(mktemp -t pad2po.XXXXXX) || exit 1 # POT content -> PO content
-TMP4=$(mktemp -t pad2po.XXXXXX) || exit 1 # Pad content / processed tr. strings
-trap 'rm -f "$TMP1" "$TMP2" "$TMP3" "$TMP4"' EXIT
-
-# List the translated pads in the working directory.
-  ls EnFr-*.txt > $TMP1 2>/dev/null || true
-
-if [ ! -s $TMP1 ]; then
-  echo "*** Il n'y a pas de pad dans le dossier de travail. Bye."
-  exit 1
+if [ -f /usr/bin/kwrite ]; then
+  editor=kwrite
+elif [ -f /usr/bin/gedit ]; then
+  editor=gedit
+else
+  editor=vi
 fi
 
-# List the POs.
-ls *.fr.po > $TMP2 2>/dev/null || true
+echo -e "\n## pad2po : Conversion d'un pad en fichier PO ##\n"
 
-# Remove .txt files from the list if they are already converted to PO.
-if [ -s $TMP2 ]; then
-  while read po; do
-    name=${po%.fr.po}
-    sed -i "/$name/d" $TMP1
-  done < $TMP2
+## File input
+
+  # 1. via the Nautilus script (new_txt is already set),
+
+  # 2. via the application launcher of the contextual menu or the command line,
+input=$1
+if [ -z "$new_txt" ]; then
+  new_txt=$input
+fi
+if [ -n "$new_txt" ]; then
+  echo "*** Fichier TXT à convertir : $new_txt"
+else
+
+  # 3. via the application menu (drag-and-drop the file or enter it directly).
+  echo "*** Quel est le fichier TXT à convertir ?"
+  read new_txt
 fi
 
-if [ ! -s $TMP1 ]; then
-  echo "*** Il n'y a pas de nouveau pad dans le dossier de travail. Bye."
-  exit 1
+# Clean up the input to get the full path, and extract the name of the
+# document.
+path=${new_txt//\'/}
+file=${path##*/}
+name1=${file%.txt}
+name=${name1#FrEn-}
+
+# Check for non-zero content and txt extension.
+if [ -n "$path" -a "$name" != "$file" ]; then
+  exit_code=0
+
+  # Create temporary files.
+  TMP1=$(mktemp -t pad2po.XXXXXX) || exit 1 # Pad
+  TMP2=$(mktemp -t pad2po.XXXXXX) || exit 1 # Translated strings / header
+  TMP3=$(mktemp -t pad2po.XXXXXX) || exit 1 # POT content -> PO content
+  TMP4=$(mktemp -t pad2po.XXXXXX) || exit 1 # Pad content / processed tr. strings
+  TMP5=$(mktemp -t pad2po.XXXXXX) || exit 1 # Links
+  trap 'rm -f "$TMP1" "$TMP2" "$TMP3" "$TMP4" "$TMP5"' EXIT
+
+## Link insertion
+
+  # Make a working copy of the translated pad.
+  cp $path $TMP1
+
+  # Put the links aside.
+  sed -n '/<lnk no./,$ p' $TMP1 > $TMP5
+
+  # If indeed there are links,
+  if [ -s $TMP5 ]; then
+    # Escape the & which are found in some links.
+    sed -i 's,&,\\&,g' $TMP5
+    # Remove the string number (if created by html2pad).
+    sed -i 's,^#[0-9]\+~,,' $TMP5
+    # remove the original strings,
+    sed -i -e '/<lnk no./ {N;N; s,^\(<lnk no.[0-9]\+>\)\n.*\n\(.\+\)$,\1\2,}' \
+           -e '/<lnk no./ {N; s,^\(<lnk no.[0-9]\+>\)\n\(.\+$\),\1\2,}' $TMP5
+
+    # and insert the translated links (if any) where they belong.
+    i=1
+    while link=$(grep "<lnk no.$i>" $TMP5) ; do
+      sed -i "s|href={$i}|href=\"$link\"|" $TMP1
+      i=$(( i + 1 ))
+    done
+    # Remove the link numbers and the list of links from the text.
+    sed -i -e '/^<lnk no./,$ d' \
+           -e 's,<lnk no\.[0-9]\+>,,g' $TMP1
+    # Remove the link numbers and the list of links from the text.
+    sed -i -e '/^<lnk no./,$ d' \
+           -e 's,<lnk no\.[0-9]\+>,,g' $TMP1
+  fi
+
+## String replacement
+
+  # Remove the pot header and footer.
+  sed '1,/"Content-Transfer-Encoding:/d' $wdir/$name.pot > $TMP3
+  sed -i '/^#. TRANSLATORS: Use space (SPC)/,$d' $TMP3
+  # Make sure all the « msgstr "" » in the pot are empty.
+  sed -i '/^msgstr ""$/ {N; s,^msgstr ""\n",msgstr ",}' $TMP3
+
+  # Select the pad contents. The pad may have been created by pot2pad (the
+  # string label starts with "#.") or html2pad (the label starts with
+  # "#[0-9]").
+  grep -A2 "^#\(\.\|[0-9]\)" $TMP1 > $TMP2  || true
+  # Print the translated strings: one line out of 4, starting at line 3.
+  # Why 4? That's because grep -A2 adds a separator line.
+  sed -n '3~4'p $TMP2 > $TMP4
+
+  if grep "[[:print:]]" $TMP4 > /dev/null ; then
+
+    # Initialize warnings.
+    exit_code=0
+    rm -f $wdir/$name.warn
+
+    # Escape the "&".
+    sed -i 's,&,\\\\&,' $TMP4
+
+    # Start a counter for the strings.
+    n=0
+
+    # Replace pot msgstr's with pad msgstr's.
+    while read translation; do
+      let n=n+1
+      sed_exit_code=0
+
+      if [ -z "$translation" ]; then
+        echo "La chaîne $n n'a pas été traduite." >> $wdir/$name.warn \
+        && exit_code=2
+      fi
+
+      # Check for possible fuzzy strings (containing *...* or |).
+      if [[ "$translation" = *§*§* ]]; then
+         echo "Il reste probablement une incertitude
+    délimitée par \"§\" dans la chaîne $n." >> $wdir/$name.warn \
+      && exit_code=2
+      fi
+      if [[ "$translation" =~ '|' ]]; then
+        echo "Il reste un choix à faire dans la chaîne $n
+    (options séparées par \"|\")." >> $wdir/$name.warn && exit_code=2
+      fi
+
+      # Replace pot msgstr's with translated strings, identified by a number.
+      sed -i "0, /^msgstr \"\"/ s||$n $translation|" $TMP3 \
+      2>/dev/null || sed_exit_code=$?
+
+      # Sed gives an error when it sees a vertical bar in the text. In this
+      # case, replace with the string number only.
+      if (( "$sed_exit_code" == 1 )); then
+        sed -i "0, /^msgstr \"\"/ s||$n |" $TMP3
+        echo "La chaîne $n n'a pas pu être insérée." >> $wdir/$name.warn \
+        && exit_code=2
+      fi
+    done < $TMP4
+
+    # Replace the numbers with "msgstr", escape the internal double quotes in
+    # msgstr's and add double-quote delimiters.
+    sed -i -e 's,^[0-9]\+ ,msgstr ,' \
+           -e '/^msgstr/ s,",\\",g' \
+           -e 's,^msgstr \(.*\)$,msgstr "\1",' $TMP3
+    # Isolate the pot header.
+    sed '/^#. type: Content of:/,$d' $wdir/$name.pot |
+    sed '$d' > $TMP2
+    # Fill it out with generic data.
+    sed -i -e 's,charset=CHARSET,charset=utf-8,' \
+           -e 's,Encoding: ENCODING,Encoding: 8bit,' \
+           -e 's,LANGUAGE <LL@li.org>,French <trad-gnu@april.org>,' \
+           -e 's,^# LANGUAGE translation,# French translation,' \
+           -e "s,# Copyright (C) YEAR,# Copyright (C) $(date +'%Y')," \
+           -e '/^# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.$/d' \
+           -e '/^"Language-Team:/ a"Language: fr\\n"' $TMP2
+    # Isolate the pot footer
+    sed '1,/#. TRANSLATORS: Use space (SPC)/d' $wdir/$name.pot > $TMP4
+
+    # Add the header and footer to the new po.
+    cat $TMP2 $TMP3 $TMP4 > $wdir/$name.fr.po
+
+    # Display the warning messages and the translated page.
+    $editor $wdir/$name.fr.po $wdir/$name.warn
+
+  else
+    echo "*** Le pad ne semble pas avoir été traduit du tout."
+    echo "    Valider pour fermer le terminal."
+    read
+    exit 2
+  fi
 
 else
-  while read new_txt; do
-    name1=${new_txt%.txt}
-    name=${name1:5}
-
-    # Remove the pot header and footer.
-    sed '1,/"Content-Transfer-Encoding:/d' $name.pot > $TMP3
-    sed -i '/^#. TRANSLATORS: Use space (SPC)/,$d' $TMP3
-    # Make sure all the « msgstr "" » in the pot are empty.
-    sed -i '/^msgstr ""$/ {N; s,^msgstr ""\n",msgstr ",}' $TMP3
-
-    # Select the pad contents. The pad may have been created by pot2pad (the
-    # string label starts with "#.") or html2pad (the label starts with
-    # "#[0-9]").
-    grep -A2 "^#\(\.\|[0-9]\)" EnFr-$name.txt > $TMP2  || true
-    # Print the translated strings: one line out of 4, starting at line 3.
-    # Why 4? That's because grep -A2 adds a separator line.
-    sed -n '3~4'p $TMP2 > $TMP4
-
-    if grep "[[:print:]]" $TMP4 > /dev/null ; then
-
-      # Escape the "&".
-      sed -i 's,&,\\\\&,' $TMP4
-
-      # Start a counter for the strings.
-      n=0
-
-      # Replace pot msgstr's with pad msgstr's.
-      while read translation; do
-        let n=n+1
-        sed_exit_code=0
-
-        if [ -z "$translation" ]; then
-          echo "*** La chaîne $n n'a pas été traduite."
-        fi
-
-        # Check for possible fuzzy strings (containing *...* or |).
-        if [[ "$translation" = *§*§* ]]; then
-           echo "*** Il reste probablement une incertitude
-    délimitée par \"§\" dans la chaîne $n."
-        fi
-        if [[ "$translation" =~ '|' ]]; then
-          echo "*** Il reste un choix à faire dans la chaîne $n
-    (options séparées par \"|\")."
-        fi
-
-        # Replace pot msgstr's with translated strings, identified by a number.
-        sed -i "0, /^msgstr \"\"/ s||$n $translation|" $TMP3 \
-        2>/dev/null || sed_exit_code=$?
-
-        # Sed gives an error when it sees a vertical bar in the text. In this
-        # case, replace with the string number only.
-        if (( "$sed_exit_code" == 1 )); then
-          sed -i "0, /^msgstr \"\"/ s||$n |" $TMP3
-          echo "*** La chaîne $n n'a pas pu être insérée."
-        fi
-      done < $TMP4
-
-      # Replace the numbers with "msgstr", escape the internal double quotes in
-      # msgstr's and add double-quote delimiters.
-      sed -i -e 's,^[0-9]\+ ,msgstr ,' \
-             -e '/^msgstr/ s,",\\",g' \
-             -e 's,^msgstr \(.*\)$,msgstr "\1",' $TMP3
-
-      # Isolate the pot header.
-      sed '/^#. type: Content of:/,$d' $name.pot |
-      sed '$d' > $TMP2
-      # Fill it out with generic data.
-      sed -i -e 's,charset=CHARSET,charset=utf-8,' \
-             -e 's,Encoding: ENCODING,Encoding: 8bit,' \
-             -e 's,LANGUAGE <LL@li.org>,French <trad-gnu@april.org>,' \
-             -e 's,^# LANGUAGE translation,# French translation,' $TMP2
-
-      # Isolate the pot footer
-      sed '1,/#. TRANSLATORS: Use space (SPC)/d' $name.pot > $TMP4
-
-      # Add the header and footer to the new po.
-      cat $TMP2 $TMP3 $TMP4 > $name.fr.po
-      echo "=== $name.fr.po a été créé."
-
-    else
-      echo "*** Le pad ne semble pas avoir été traduit du tout."
-    fi
-
-  done < $TMP1
+  echo "*** Ce n'est pas un fichier TXT, ou bien il est vide."
+  echo "    Valider pour fermer le terminal."
+  read
+  exit 1
 fi
 
-exit
+exit $exit_code
diff --git a/pot2pad b/pot2pad
--- a/pot2pad
+++ b/pot2pad
@@ -1,99 +1,176 @@
 #!/bin/bash
 
-# PAD to PO converter
+# NAME
+#    pot2pad - POT to PAD converter
 
+# SYNOPSIS
+#    pot2pad [/path/to/NAME.pot]
 
-# Overview:
-# This script removes some of the features of a POT file to make it suitable
-# for the translation pad.
+# DESCRIPTION
+#    This script removes some of the features of a POT file to make it
+#    suitable for the translation pad. It is somewhat interactive and can
+#    be launched from the application and contextual menus of GNOME or KDE.
 
-# Requirements:
-# - The working directory should contain the POT file (NAME.pot) and
-#   (optionally) pad-header-fr.
-# - The name of the pad should start with "EnFr-" (assuming translation from
-#   English to French).
+# REQUIREMENTS
+#    * The working directory (wdir) is $HOME/pad. This can be changed by
+#      modifying one line in the script.
+#    * If a pad header is used, it must be in the working directory. Its
+#      name should be "pad-header-gnu".
 
-# How-to:
-# - Launch the script or run it from a terminal.
-# - To convert the same NAME.pot again, the corresponding .pad file needs
-#   to be removed from the working directory.
+# OPTIONS
+#    None yet.
+
+# OUTPUT, WARNINGS and ERRORS
+#    NAME.pad is created in the working directory. This is a plain text
+#    file which can be copied directly to the pad page.
+#    The exit code is 1 if the input file does not have the .pot extension
+#    or is empty, 0 otherwise.
+
+# HOW-TO for GNOME and KDE
+#    The POT file to be converted can be anywhere in the filetree, but
+#    preferably at the proper place in the www directory.
+
+#    1. [optional] Edit pad-header-gnu or remove it.
+
+#    2. Launch the script from the contextual menu of the file to be pro‐
+#       cessed (Nautilus or Konqueror; application POT2PAD). NAME.pad is
+#       created in the working directory.
+
+#       Note on file associations:
+
+#       In Konqueror, you may edit the preferred applications for opening
+#       POT files from the menubar: Edit > Edit File Type...
+
+#       In Nautilus, this is done from the contextual menu. If the
+#       launcher is not listed, you will have to edit
+#       ~/.local/share/applications/mimeapps.list. For instance:
+#          [Added Associations]
+#          [...]
+#          text/pot=pot2pad.desktop
+#          [...]
+
+#    2a. Alternatively, use the POT2PAD launcher from the application menu
+#       (the default category is "Other" in GNOME, "Lost and Found" in KDE).
+#       At the prompt,
+#       - drag and drop the file into the GNOME Terminal,
+#       - or drag and drop the file into the Konsole, then choose "Paste
+#         as text".
+
+#    3. Copy NAME.pad to the pad page.
+
+# AUTHOR
+#    Therese <godef.th@free.fr>
 
 # Copyright (C) 2013 Whoever.
 # You may redistribute this script and/or modify it under the terms of the
 # Creative Commons CC0 license
 # (http://creativecommons.org/publicdomain/zero/1.0/legalcode).
 
+
+wdir=$HOME/pad
+
 set -e
-mkdir -p $HOME/pad && cd $HOME/pad
+mkdir -p $wdir
 
-echo "
- ## pot2pad : Préparation d'un fichier POT pour le pad de traduction ##
-"
-
-# Check for the presence of the pad header.
-if [ ! -f pad-header-fr ]; then
-  echo "*** Il n'y a pas d'en-tête pad dans le dossier de travail.
-    Voulez-vous créer un pad sans en-tête ?
-    \"Oui\" = [Entrée]   \"Non\" = autre touche"
-  read -s -n1 OK
-  if [ -n "$OK" ]; then
-    echo "*** Bye"
-    exit 1
-  fi
-fi
-
-# Create temporary files.
-TMP1=$(mktemp -t pot2pad.XXXXXX) || exit 1 # POT list, pruned
-TMP2=$(mktemp -t pot2pad.XXXXXX) || exit 1 # List of untranslated pads
-TMP3=$(mktemp -t pot2pad.XXXXXX) || exit 1 # POT content -> pad content
-trap 'rm -f "$TMP1" "$TMP2" "$TMP3" "$TMP4"' EXIT
-
-# List the POTs in the working directory.
-  ls *.pot > TMP1 2>/dev/null || true
-
-if [ ! -s TMP1 ]; then
-  echo "*** Il n'y a pas de pot dans le dossier de travail. Bye."
-  exit 1
+if [ -f /usr/bin/kwrite ]; then
+  editor=kwrite
+elif [ -f /usr/bin/gedit ]; then
+  editor=gedit
+else
+  editor=vi
 fi
 
 
-# List the pads.
-ls *.pad > $TMP2 2>/dev/null || true
+echo -e "\n ## Préparation d'une page HTML pour le pad de traduction ##\n"
 
+## File input
 
-# Remove POT files from the list if they are already converted to pad.
-if [ -s $TMP2 ]; then
-  while read pad; do
-    name1=${pad%.pad}
-    name=${name1:5}
-    sed -i "/$name/d" $TMP1
-  done < $TMP2
+  # 1. via the Nautilus script (new_pot is already set)
+
+  # 2. via the application launcher of the contextual menu or the command line,
+input=$1
+if [ -z "$new_pot" ]; then
+  new_pot=$input
+fi
+if [ -n "$new_pot" ]; then
+  echo "*** Fichier HTML à convertir : $new_pot"
+else
+
+  # 3. via the application menu (drag-and-drop the file or enter it directly).
+  echo "*** Quel est le fichier HTML à convertir ?"
+  read new_pot
 fi
 
-if [ ! -s TMP1 ]; then
-  echo "*** Il n'y a pas de nouveau pot dans le dossier de travail. Bye."
-  exit 1
+# Clean up the input to get the full path, and extract the name of the
+# document.
+path=${new_pot//\'/}
+file=${path##*/}
+name=${file%.pot}
+
+# Get the URL of the original page (assuming the POT is in the www directory).
+# Pure laziness: that saves writing it on top of the pad. If there is no
+# /www/ in the path, the URL will be wrong. No big deal.
+pot_url="http://www.gnu.org/${path/*\/www\//}"
+url1=${pot_url/\/po\//\/}
+url=${url1%.pot}
+
+# Check for non-zero content and .pot extension.
+if [ "$name" != "$file" -a -n "$path" ]; then
+
+  # Create temporary files (same numbers as in html2pad).
+  TMP3=$(mktemp -t pot2pad.XXXXXX) || exit 1 # POT content -> pad content
+  TMP4=$(mktemp -t pot2pad.XXXXXX) || exit 1 # Interm. in link processing
+  TMP5=$(mktemp -t pot2pad.XXXXXX) || exit 1 # Interm. in link processing
+  trap 'rm -f "$TMP3" "$TMP4" "$TMP5"' EXIT
+
+## Convert the POT
+
+  # Select contents (starting at <h2>).
+  sed '1,/"Content-Transfer-Encoding:/d' ${path} > $TMP3
+  sed -i '/#. TRANSLATORS: Use space (SPC)/,$d' $TMP3
+
+  # Unformat.
+  sed -i ':egin /^msgid/ {N; s,"\n",,; begin}' $TMP3
+  sed -i -e 's,^msg\(id\|str\) ",,' \
+         -e 's,"$,,' $TMP3
+
+  # Label the links.
+  awk 'BEGIN {RS=ORS="</a>"}
+      {gsub ( /href=/, "href={"NR"}<lnk no."NR">", $0 ); print}
+      END {RS=ORS="\n"}' $TMP3 > $TMP4
+  # Remove an extra </a> that was added by awk.
+  sed -i 's,^</a>$,,' $TMP4
+
+  # Delete the links from the text.
+  sed -e 's,<lnk no.[0-9]\+>[^>]*>,>,g' $TMP4 > $TMP3
+
+  # Extract the links and add them after the text.
+  sed -e 's,\(<lnk no.[0-9]\+>[^>]*\)>,\1\n,g' $TMP4 > $TMP5
+  sed -i 's,<lnk,\n<lnk,g' $TMP5
+  sed -n '/^<lnk/p'  $TMP5 >> $TMP3
+
+  # Remove the escaped double quotes.
+  sed -i 's,\\",,g' $TMP3
+
+  # Split after the link labels and add 2 blank lines after each link.
+  sed -i 's,^\(<lnk no.[0-9]\+>\),\n\n\1\n,' $TMP3
+
+  # Optionally add a header.
+  echo "Nom du pad : FrEn-$name" > $wdir/FrEn-$name.pad
+  echo "Traduction en français de $url" >> $wdir/FrEn-$name.pad
+  cat $wdir/pad-header-gnu $TMP3 >> $wdir/FrEn-$name.pad
+
+  # Add a blank line at the end (in case there are links).
+  echo "" >> $wdir/FrEn-$name.pad
+
+  # Display the pad.
+  $editor $wdir/FrEn-$name.pad
 
 else
-  while read new_pot; do
-    name=${new_pot%.pot}
-
-    # Select POT contents (starting at <h2>).
-    sed '1,/"Content-Transfer-Encoding:/d' $name.pot > $TMP3
-    sed -i '/#. TRANSLATORS: Use space (SPC)/,$d' $TMP3
-    # Unformat it.
-    sed -i ':egin /^msgid/ {N; s,"\n",,; begin}' $TMP3
-    sed -i -e 's,^msg\(id\|str\) ",,' \
-           -e 's,"$,,' $TMP3
-    # Add the information for translators, if any.
-    if [ -f pad-header-fr ] && [ -n pad-header-fr ]; then
-      cat pad-header-fr $TMP3 > EnFr-$name.pad
-      echo "=== EnFr-$name.pad a été créé."
-    else
-      mv $TMP3 $name.pad
-      echo "=== EnFr-$name.pad a été créé sans en-tête."
-    fi
-  done < TMP1
+  echo "*** Ce n'est pas un fichier POT."
+  echo "    Valider pour fermer le terminal."
+  read
+  exit 1
 fi
 
-exit
+exit 0
